from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 760)
        self.img_tab = QtWidgets.QTabWidget(MainWindow)
        self.img_tab.setGeometry(QtCore.QRect(30, 30, 504, 704))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.img_tab.setFont(font)
        self.img_tab.setObjectName("img_tab")
        self.input_img_tab = QtWidgets.QWidget()
        self.input_img_tab.setObjectName("input_img_tab")
        self.inp_img = QtWidgets.QLabel(self.input_img_tab)
        self.inp_img.setGeometry(QtCore.QRect(1, 0, 504, 672))
        self.inp_img.setText("")
        self.inp_img.setObjectName("inp_img")
        self.img_tab.addTab(self.input_img_tab, "")
        self.processed_img_tab = QtWidgets.QWidget()
        self.processed_img_tab.setObjectName("processed_img_tab")
        self.proc_img = QtWidgets.QLabel(self.processed_img_tab)
        self.proc_img.setGeometry(QtCore.QRect(1, 0, 504, 672))
        self.proc_img.setText("")
        self.proc_img.setObjectName("proc_img")
        self.img_tab.addTab(self.processed_img_tab, "")
        self.file_name = QtWidgets.QLineEdit(MainWindow)
        self.file_name.setGeometry(QtCore.QRect(565, 190, 400, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.file_name.setFont(font)
        self.file_name.setObjectName("file_name")
        self.browse = QtWidgets.QPushButton(MainWindow)
        self.browse.setGeometry(QtCore.QRect(785, 130, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.browse.setFont(font)
        self.browse.setObjectName("browse")
        self.title = QtWidgets.QLabel(MainWindow)
        self.title.setGeometry(QtCore.QRect(565, 30, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.log_box = QtWidgets.QTextBrowser(MainWindow)
        self.log_box.setGeometry(QtCore.QRect(565, 240, 400, 250))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.log_box.setFont(font)
        self.log_box.setObjectName("log_box")
        self.start_button = QtWidgets.QPushButton(MainWindow)
        self.start_button.setGeometry(QtCore.QRect(565, 130, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")

        self.retranslateUi(MainWindow)
        self.img_tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bottle inspection system"))
        self.img_tab.setTabText(self.img_tab.indexOf(self.input_img_tab), _translate("MainWindow", "Input image"))
        self.img_tab.setTabText(self.img_tab.indexOf(self.processed_img_tab), _translate("MainWindow", "Processed image"))
        self.browse.setText(_translate("MainWindow", "Browse"))
        self.title.setText(_translate("MainWindow", "Bottle inspection system"))
        self.start_button.setText(_translate("MainWindow", "Start"))
